#download the base image
FROM ubuntu:20.04

# LABEL about the custom image
LABEL maintainer="niki.hrovatin@famnit.upr.si"
LABEL version="0.1"
LABEL description="Custom Docker image for DAQ-monitoring"

# Disable Prompt During Packages Installation
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https=2.0.6 \
        #autoconf=2.69-11.1 \
        #automake=1:1.16.1-4ubuntu6 \
        ca-certificates=20210119~20.04.2 \
        curl \
        wget \
        #libxml2 \ 
        #libxml2-dev \
        #g++=4:9.3.0-1ubuntu2 \
        git=1:2.25.1-1ubuntu3.2 \
        #libtool=2.4.6-14 \
        #make=4.2.1-1.2 \
        #pkg-config=0.29.1-0ubuntu4 \
        python3=3.8.2-0ubuntu2 \
        python3-dev=3.8.2-0ubuntu2 \
        python3-setuptools=45.2.0-1 \
        #sqlite3=3.31.1-4ubuntu0.2 \
        unzip=6.0-25ubuntu1 \
        python3-pip \
    && rm -rf /var/lib/apt/lists/*


RUN update-ca-certificates

RUN pip3 install minimalmodbus && pip3 install paho-mqtt 

RUN git clone https://gitlab.com/nikih94/arrs_or

RUN cd arrs_or &&\
	git pull &&\
    ls -l /dev/* &&\
	cd data_acquisition/client #&&\
    #python3 collect_data.py
    

